version: "3"
services:
  web: &rails_base
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      YARN_INTEGRITY_ENABLED: "false"
    volumes:
      - .:/usr/src/app
    command: bundle exec rails server -b 0.0.0.0 -p 3000
  jobs:
    ports: []
    <<: *rails_base
    command: rails jobs:work
  webpacker:
    ports: []
    <<: *rails_base
    command: ./bin/webpack-dev-server
  db:
    image: postgres:9.6-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    container_name: dev_nginx
    networks:
      default:
        aliases:
          - host-gateway
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    ports:
      - 443:443
    environment:
      RAILS_PORT: ${RAILS_PORT:-3000}
